os: linux
dist: bionic
language: ruby

jobs:
  fast_finish: true

  include:
    - name: Build using Bundler
      install: bundle install --jobs=3 --retry=3
      script: bundle exec jekyll build
    - name: Build using latest github-pages
      install:
        # `jekyll build` seems to be using Bundler if Gemfile is present:
        - rm -f -- Gemfile Gemfile.lock
        - gem install github-pages
      script: jekyll build
