# Jekyll
plugins:
  - jekyll-github-metadata
  - jekyll-remote-theme

exclude:
  - .travis.yml
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - README.md

# jekyll-github-metadata
repository: egor-tensin/egor-tensin.github.io
# jekyll-remote-theme
remote_theme: egor-tensin/jekyll-theme

# egor-tensin/jekyll-theme
bootstrap_version: 3.3.7
jquery_version: 1.12.4
html5shiv_version: 3.7.3
respond_version: 1.4.2

minified_externals: true
hide_navbar: true

personal_info:
  name: Egor Tensin
  email: Egor.Tensin@gmail.com
  cv_url: https://egor-tensin.github.io/cv/cv.pdf
  gpg:
    public_key_url: /gpg.txt
    fingerprint: 0281 0B23 3E1A 7D41 8FB1  5245 0494 6FC7 502B 539A
  projects:
    - url: /blog/
      name: My blog
    - url: /sorting-algorithms/
      name: Sorting algorithms
