# Jekyll
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor/

# Plugins
plugins:
  - jekyll-github-metadata
  - jekyll-remote-theme

# jekyll-github-metadata
repository: egor-tensin/egor-tensin.github.io
# jekyll-remote-theme
remote_theme: egor-tensin/jekyll-theme@00bf98134e4da8897ec32897a9bc88b610696d9c

# Theme settings
settings:
  project:
    license: MIT License
    license_file: LICENSE.txt
  author:
    name: Egor Tensin
    email: Egor.Tensin@gmail.com
  navbar:
    hide: true
