# Jekyll
exclude:
  - Gemfile
  - Gemfile.lock
  - Makefile
  - README.md
  - vendor/

# Plugins
plugins:
  - jekyll-github-metadata
  - jekyll-remote-theme

# jekyll-github-metadata
repository: egor-tensin/egor-tensin.github.io
# jekyll-remote-theme
remote_theme: egor-tensin/jekyll-theme@fd6e288154bd9c8813d662975420cd82668eb13e

# Theme settings
settings:
  author:
    name: Egor Tensin
    email: Egor.Tensin@gmail.com
  navbar:
    hide: true
